server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yourusername/e-commerce-config
          default-label: main
          search-paths: '{application}'
  security:
    user:
      name: config
      password: config

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 